In [43]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import  ColumnTransformer 
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [2]:
df=pd.read_csv('train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [7]:
# feature in x
X=df[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
y=df['Survived']

In [8]:
print('x shape : ',X.shape)
print('y shape : ',y.shape)

x shape :  (891, 7)
y shape :  (891,)

In [9]:
X.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [10]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [11]:
num_col=['Age','SibSp','Parch','Fare']
cat_col=['Pclass','Sex','Embarked']
num_col,cat_col

(['Age', 'SibSp', 'Parch', 'Fare'], ['Pclass', 'Sex', 'Embarked'])

In [12]:
X_train,X_test , y_train , y_test = train_test_split(X,y,random_state=42 , test_size=0.2)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 7)
(179, 7)
(712,)
(179,)

In [13]:
print(X_train.isnull().sum())
print('------------------------------------')
print(X_test.isnull().sum())
print('------------------------------------')
print(y_train.isnull().sum())
print('------------------------------------')
print(y_test.isnull().sum())

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64
------------------------------------
Pclass       0
Sex          0
Age         37
SibSp        0
Parch        0
Fare         0
Embarked     0
dtype: int64
------------------------------------
0
------------------------------------
0

### 3. Missing value filling

In [14]:
# filling age with mean/median age 
age_median=X_train['Age'].median()
age_median

np.float64(28.0)

In [15]:
X_train['Age']=X_train['Age'].fillna(age_median)
X_test['Age']=X_test['Age'].fillna(age_median)
print(X_train.isnull().sum())
print('------------------------------------')
print(X_test.isnull().sum())

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64
------------------------------------
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [16]:
# filling embarked with most frequent/mode 
embarked_mode = X_train['Embarked'].mode()[0]
embarked_mode

'S'

In [17]:
X_train['Embarked']=X_train['Embarked'].fillna(embarked_mode)
X_test['Embarked']=X_test['Embarked'].fillna(embarked_mode)
print(X_train.isnull().sum())
print('------------------------------------')
print(X_test.isnull().sum())

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64
------------------------------------
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [18]:
# filling is done over her

In [19]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male  28.0      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [20]:
X_test

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
709       3    male  28.0      1      1  15.2458        C
439       2    male  31.0      0      0  10.5000        S
840       3    male  20.0      0      0   7.9250        S
720       2  female   6.0      0      1  33.0000        S
39        3  female  14.0      1      0  11.2417        C
..      ...     ...   ...    ...    ...      ...      ...
433       3    male  17.0      0      0   7.1250        S
773       3    male  28.0      0      0   7.2250        C
25        3  female  38.0      1      5  31.3875        S
84        2  female  17.0      0      0  10.5000        S
10        3  female   4.0      1      1  16.7000        S

[179 rows x 7 columns]

### 4. Categorical/numerical encoding

In [21]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male  28.0      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [22]:
print('Encoding on : ',cat_col)
print('MinMax scaling on : ',num_col)
print('Performing Ohe on : sex and embarked')
print('Perfroming ordinal encoding on:  Pclass')

Encoding on :  ['Pclass', 'Sex', 'Embarked']
MinMax scaling on :  ['Age', 'SibSp', 'Parch', 'Fare']
Performing Ohe on : sex and embarked
Perfroming ordinal encoding on:  Pclass

In [23]:
ohe=OneHotEncoder(handle_unknown='ignore',sparse_output=False)
ohe.fit(X_train[['Sex','Embarked']])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [24]:
X_train_cat = ohe.transform(X_train[['Sex','Embarked']])
X_test_cat = ohe.transform(X_test[['Sex','Embarked']])

In [25]:
ohe.get_feature_names_out(['Sex','Embarked'])

array(['Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype=object)

In [40]:
# now performing ordinal encoding on Pclass 
oe=OrdinalEncoder()
oe.fit(X_train[['Pclass']])
X_train_pclass=oe.transform(X_train[['Pclass']])
X_test_pclass=oe.transform(X_test[['Pclass']])

In [41]:
# now oding scaling on numerical columns 
print('Perfroming scaling using minma scaler on : ',num_col)

Perfroming scaling using minma scaler on :  ['Age', 'Fare', 'SibSp', 'Parch']

In [28]:
scaler=StandardScaler()
scaler.fit(X_train[num_col])
X_train_num=scaler.transform(X_train[num_col])
X_test_num=scaler.transform(X_test[num_col])

In [29]:
# checking done or not the min max scaling 
X_train_num[:5]

array([[ 1.25364106, -0.47072241, -0.47934164, -0.07868358],
       [-0.47728355, -0.47072241, -0.47934164, -0.37714494],
       [ 0.21508629, -0.47072241, -0.47934164, -0.47486697],
       [-0.24649361,  0.37992316, -0.47934164, -0.47623026],
       [-1.78509326,  2.93185988,  2.04874166, -0.02524937]])

### done with encodings and scaling

## Column Transformer

In [32]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male  28.0      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [33]:
num_col=['Age','Fare','SibSp','Parch']
cat_col=['Sex','Embarked']
ordinal_col=['Pclass']

In [34]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),num_col),
        ('ohe',OneHotEncoder(handle_unknown='ignore',sparse_output=False),cat_col),
        ('ordinal',OrdinalEncoder(),ordinal_col)
    ]
)

In [35]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['Age', 'Fare', 'SibSp', 'Parch']),
                                ('ohe',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['Sex', 'Embarked']),
                                ('ordinal', OrdinalEncoder(), ['Pclass'])])

In [36]:
X_train_transformed=preprocessor.transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [37]:
print(X_train_transformed.shape)
print(X_test_transformed.shape)

(712, 10)
(179, 10)

In [39]:
preprocessor.get_feature_names_out()

array(['num__Age', 'num__Fare', 'num__SibSp', 'num__Parch',
       'ohe__Sex_female', 'ohe__Sex_male', 'ohe__Embarked_C',
       'ohe__Embarked_Q', 'ohe__Embarked_S', 'ordinal__Pclass'],
      dtype=object)

In [44]:
num_pipeline=Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])

In [45]:
cat_pipeline=Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])

In [46]:
ordinal_pipeline=Pipeline([
    ('encoder',OrdinalEncoder())
])

In [48]:
preprocessor=ColumnTransformer([
     ('num', num_pipeline, num_col),
    ('cat', cat_pipeline, cat_col),
    ('ordinal', ordinal_pipeline, ordinal_col)
])

In [49]:
print('Train',X_train_transformed.shape)
print('Test',X_test_transformed.shape)

Train (712, 10)
Test (179, 10)

In [50]:
# doing a outer pipeline 
final_pipeline = Pipeline([
    ('preprocessor', preprocessor)
])

In [51]:
final_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Fare', 'SibSp',
                                                   'Parch']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Sex', 'Embarked']),
                                                 ('ordinal',
                                                  Pipeline(steps=[('encoder',
                                                                   OrdinalEncoder())]),
                                                  ['Pclass'])]))])

In [52]:
X_train_transformed = final_pipeline.transform(X_train)
X_test_transformed = final_pipeline.transform(X_test)

In [53]:
X_train_transformed

array([[ 1.25364106, -0.07868358, -0.47072241, ...,  0.        ,
         1.        ,  0.        ],
       [-0.47728355, -0.37714494, -0.47072241, ...,  0.        ,
         1.        ,  1.        ],
       [ 0.21508629, -0.47486697, -0.47072241, ...,  0.        ,
         1.        ,  2.        ],
       ...,
       [ 0.90745614, -0.35580399,  1.23056874, ...,  0.        ,
         1.        ,  2.        ],
       [-1.1696534 ,  1.68320121,  0.37992316, ...,  0.        ,
         1.        ,  0.        ],
       [-0.63114352,  0.86074761, -0.47072241, ...,  0.        ,
         1.        ,  0.        ]], shape=(712, 10))

In [54]:
X_test_transformed

array([[-0.09263364, -0.33390078,  0.37992316, ...,  0.        ,
         0.        ,  2.        ],
       [ 0.13815631, -0.42528387, -0.47072241, ...,  0.        ,
         1.        ,  1.        ],
       [-0.7080735 , -0.47486697, -0.47072241, ...,  0.        ,
         1.        ,  2.        ],
       ...,
       [ 0.67666619, -0.02308312,  0.37992316, ...,  0.        ,
         1.        ,  2.        ],
       [-0.93886345, -0.42528387, -0.47072241, ...,  0.        ,
         1.        ,  1.        ],
       [-1.93895323, -0.30589933,  0.37992316, ...,  0.        ,
         1.        ,  2.        ]], shape=(179, 10))